### ISSUE TITLE
Not working on my System

### ISSUE THREAD

**Issue by Surendrajat** [berkantkz/wallpapers-i-like#1]
Current system:
OS: PornHub OS 18.69
GLibc: 2.1

I am staring at this wallpaper but I don't seem to like it (expect ofc what the woman is hiding)... The `I like` part doesn't seem to work. I'll open a PR for that if the maintainer allows that. :(

**Comment by berkantkz** [comment]
Dude! It does not refer to the objects/people on the image but to the whole pic! Don't take it that hot 😉 haha

**Comment by Surendrajat** [comment]
Seems like a limitation. Closing xD
